### ISSUE TITLE
CSS Utility classes

### ISSUE THREAD

**Issue by nickcolley** [hoodiehq/hoodie-app-tracker#11]
I'm wondering if we could refactor some of the code to avoid utility classes, or give them longer more meaningful names.

At the moment we have the equivalent of single letter variable names that requires you to read the source code to understand what's going on, could be confusing to new people to the codebase.

I can put together a PR if this is something that we want to do.

cc @jsimplicio

**Comment by gr2m** [comment]
@nickcolley yes I agree. But there are still a few features left, so I’d finish that first with @jsimplicio, and then we do a clean up of the code, would that be ok with you?

**Comment by nickcolley** [comment]
Yeah, that sense, :+1:

**Comment by jsimplicio** [comment]
Yep we can change some things, I made utility classes for some reason now there are quite a lot. :sweat_smile:

**Comment by jsimplicio** [comment]
Should we close this?

**Comment by gr2m** [comment]
yes, thanks :)
