### ISSUE TITLE
Bug: Cannot delete tracked item

### ISSUE THREAD

**Issue by Litarhis** [hoodiehq/hoodie-app-tracker#138]
I track 2 items and when I try to delete one of those (no matter which) console throws back the following error: 
<img width="960" alt="deletionerror" src="https://cloud.githubusercontent.com/assets/15073846/24076473/5606fc36-0c3a-11e7-89a1-7bb48fb95f9a.PNG">

I followed this commands:
"`cloned repo`"
npm install
npm start

**Comment by gr2m** [comment]
We recently had pretty big update: https://github.com/hoodiehq/hoodie/releases/tag/v28.0.0

Among other things, `doc.id` is now `doc._id` (same as it is in PouchDB and CouchDB). My guess is that we pass in an `id` property where we should pass in `_id` instead.

Can you have a look if you find something out?

**Comment by Litarhis** [comment]
@gr2m, I am afraid I am a bit busy these days in order to resolve that issue 🙁 . I just came up to this while playing with the app and found it useful to report it. So, to make it clear to the assignee, hoodie tracker needs some updates in order to follow the new hoodie breaking version? Shouldn't those errors had to be prevented in #136 ?

**Comment by sdvg** [comment]
Looks like @gr2m fixed this in https://github.com/hoodiehq/hoodie-app-tracker/commit/6b9fe7a06bd62c58627062e5eb7cdbc1f44df3e2 :)

I couldn't reproduce the issue the latest version.
