### ISSUE TITLE
Disable username / password change forms and link to issues

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-app-tracker#15]
This three for username change:
- [ ] https://github.com/hoodiehq/hoodie-server-account/issues/79
- [ ] https://github.com/hoodiehq/hoodie-client-account/issues/75
- [ ] https://github.com/hoodiehq/hoodie-server-account/issues/80

These two for password change
- [ ] https://github.com/hoodiehq/hoodie-client-account/issues/75
- [ ] https://github.com/hoodiehq/hoodie-server-account/issues/80

**Comment by sdvg** [comment]
@gr2m The linked issues are all resolved, changing username (email) and password works. Can we close this issue?

**Comment by gr2m** [comment]
Yes, thanks for looking into it Stefan!
