### ISSUE TITLE
Service worker

### ISSUE THREAD

**Issue by fozy81** [hoodiehq/hoodie-app-tracker#157]
Would adding a service worker js be useful to make the app offline capable? :thinking: 

Pros :+1: 
- Makes app work offline :sunglasses: 

Cons :-1: 
- Adds little more complexity to code :hammer_and_wrench:  :computer: 
- Not supported by all browsers :frowning_face: 
- May not notice much difference if developing on local host 

If you think it's worth adding, happy to make PR :smile:

**Comment by gr2m** [comment]
Hey @fozy81 :) in general, heck yeah, absolutely! 

Making Hoodie Client Service Worker compatible is a bit of a challenge, something I want to tackle for the next big milestone.

I’d say maybe to not add it to this repository directly, but if you want to create a fork and we can link to that fork, that would work? That way we can keep this very simple but at the same time show people how to make the app work offline with Service Worker?

**Comment by fozy81** [comment]
@gr2m I've add the basic service worker here: https://github.com/fozy81/hoodie-app-tracker
with some of your code copied from hoodie-camp-tutorial :+1: .

So should give people a favour of offline web app.

Couple issues:
- Some console log errors: No response when fetching `hoodie/store/api/user` files
- I've not written any tests for this
- One existing test is failing...`Subtest: App Tracker`...`Callback was already called.`

**Comment by gr2m** [comment]
Testing web apps is very hard, I created the [selsa](https://github.com/gr2m/selsa) package to implement some best practises, but at the end of the day, it’s using Selenium and Selenium tends to break regularly, unfortunately. I don’t blame them, they are taking on an incredible hard task :)

But maybe for our case, we should drop it and use something like https://github.com/GoogleChrome/puppeteer. I’m also eager to try https://www.cypress.io :)

**Comment by fozy81** [comment]
I'll take a look...may take a little while to dive into the details.

**Comment by fozy81** [comment]
Update: I've tried out cypress - mainly because it has brilliant [docs](https://docs.cypress.io/guides/overview/why-cypress.html). I've added a couple of tests, mainly copied from an example [test file for todoMVC](https://github.com/cypress-io/cypress-example-todomvc/blob/master/cypress/integration/app_spec.js) and from the existing tests. Should be straightforward to convert the existing tests to cypress. So will work my way through them and see how it goes. A good learning experience if nothing else. Testing in JS is new to me, so starting to glimpse the magic involved in writing testing libraries for browsers/web apps...

**Comment by gr2m** [comment]
awesome :) I'm open to migrate to Cypress

**Comment by fozy81** [comment]
Hi, I've written some tests using Cypress (see summary below), added a manifest.json and got service worker running. In general works offline okay. Could add on/offline indicator. Also trims white space from input items, and converts createdAt date/time to Date object before sorting, allowing sorting to be consistent for testing. 

One test failing - can't sign-out(?). Anything other tests needed? Or any other suggestions?  

1. Hoodie Tracker About Page
    About page
      ✓ should allow me to visit About page
 2.  Hoodie Tracker Account Page
    Account page
      ✓ should allow me visit Account page 
      ✓ should allow me to create an account
      ✓ should sign me in when account is created
      ✓ should allow me to delete account 
      ...Error: Database "user/5fsfadx" does not exist...
      x) should allow me to sign out
 3. Hoodie Tracker Home Page
    Visit home page
      ✓ should load index.html successfully 
    When page is initially opened
      ✓ should focus on the item input field 
    No Items
      ✓ should hide item table
    Add items
      ✓ should allow me to add items 
      ✓ should clear text input field when an item is added 
      ✓ should trim text input 
      ✓ should show remove all button 
    Table of items
      ✓ should allow me to edit an item
      ✓ should allow me to delete an item

**Comment by gr2m** [comment]
happy to help look into the sign out error. I’ll have some time on Friday for Open Source work, looking forward to see how the Cypress setup works :)

**Comment by fozy81** [comment]
Thanks, that's great. No pressure - whenever you find time. Cypress seems very nice.

**Comment by fozy81** [comment]
Hi @gr2m 
Here's the forked tracker app with service worker hosted on now/zeit:
https://hoodie-app-tracker.now.sh/

Also passing Chrome PWA tests :fireworks: :+1: 
![screenshot from 2017-11-12 12 35 44](https://user-images.githubusercontent.com/2878163/32699147-b3957f6a-c7a8-11e7-8270-bf0335666ba1.png)

forked code is here:
https://github.com/fozy81/hoodie-app-tracker

**Comment by gr2m** [comment]
I’m so sorry I didn’t get back to you earlier, I’m a bit overwhelmed with my inboxes :( This looks great though! Some people were asking about Hoodie + ServiceWorker at Offline Camp, too, I’ll point them to your fork! 

I’m checking out your fork now, we should definitely mention it in the hoodie-app-tracker README – or even make it the default app altogether 😁

**Comment by gr2m** [comment]
wow, this is really great work Tim! Also great work on adding Cypress! I wonder if we can run the tests somehow automatically in `npm test`? Do you know if they can be run headless so we can run the tests on Travis CI? 

If you like, we can start a pull request from you fork :) I would suggest we document the addition of Service Worker in the README and also the about page. (The about page in the app needs some updates anyway :) )

What do you think?

**Comment by fozy81** [comment]
No problem, thanks for getting back. I appreciate maintaining open source projects takes a lot of time. And you got to fit it around everything else.

I removed the package.json script to run 'npm test' but can put that back in to run cypress headlessly. Shouldn't be a problem for Travis CI. Just got one failing test currently. I think it is to do with running locally (can't sign-out). 
 
Should the old tests be removed? Are they still useful - anything missing from Cypress tests? Cypress is aimed at integration testing not so much at unit testing/code coverage.

I'll create a pull request, and update the readme with mention of the service worker, app manifest (only really works for Chrome atm) and how to run Cypress tests (both headless and with browser).

**Comment by gr2m** [comment]
> Should the old tests be removed?

Yes, please. I’m so excited and hopeful for a future without Selenium :)

> Cypress is aimed at integration testing not so much at unit testing/code coverage.

For end-user applications I don’t see much point in unit tests or code coverage, doing the end-to-end tests is perfect. We just want to check if all user-facing features work.

When I have the feeling that I need unit tests in an app, it’s usually a sign that there is something worth extracting into its own library, which then can have full test coverage.

> only really works for Chrome atm

Oh I didn’t test it with other browsers yet. I assume that if ServiceWorkers is not supported in the browser, it will just work as before?

**Comment by fozy81** [comment]
Great, thanks for the feedback. I'll remove the old tests. Your thoughts on unit testing mirrored what i was thinking but just wanted to check.

Service worker - yep, if service worker not supported then will work as before. 

> only really works on Chrome atm

The extra features provided by the manifest.json i.e. adding an icon to android home screen/apps and having a splash page when app is loading. But some manifest features do work by default on Firefox too. I think the manifest is worth including because it makes the app really nice on android phones and maybe iOS someday...

I'll get to work polishing this up! 👍

**Comment by fozy81** [comment]
Features added in pull request https://github.com/hoodiehq/hoodie-app-tracker/pull/161
