### ISSUE TITLE
the value of Input  change Email is "undefined"

### ISSUE THREAD

**Issue by elvinaliyev87** [hoodiehq/hoodie-app-tracker#162]
When user have clicked change email, he didn't see current email in the input. 

![changeemail](https://user-images.githubusercontent.com/32110355/33122961-3467ffe6-cf92-11e7-9436-3c88b41331f3.PNG)

**Comment by gr2m** [comment]
thank you @elvinaliyev87 I was able to reproduce the bug :)

I think the problem is this line:

**Comment by fozy81** [comment]
Looks like this is fixed now :+1: - will close issue
