### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by kylebakerio** [hoodiehq/hoodie-app-tracker#174]
https://tracker.hood.ie/ just fails. `Err: connection refused` in chrome

**Comment by fozy81** [comment]
Same here, looks like it needs a refresh @gr2m

**Comment by gr2m** [comment]
yeah, it's a setup with Docker and Digital Ocean that I don’t know how it works. 

What I would suggest to do instead is to deploy to glitch instead. It supports file system writes so we can use it with the fs adapter, it'd be super easy and people could directly remix the app and play around with the code in their editor. We have an example deployed here: http://hoodie.glitch.me/

I have continous deployment to glitch setup for https://github.com/gr2m/glitch-github-app. If anyone would like to take it on I’d be happy to help out if you get stuck. Glitch is really fun and great developer experience

**Comment by fozy81** [comment]
I wondered about the couchdb backend? The Docker deploy includes couchdb but not sure glitch can host that part - perhaps need host a couchdb separately? But even without couchdb the app will run as demo (just without permanent saving of data) so will take a look at deploying to glitch. Will assign myself to the task when got time if anyone else wants to try jump in :smiley:

**Comment by gr2m** [comment]
I’m sorry I should have been more clear. When you install Hoodie locally on your machine it is using [`pouchdb-adapter-fs`](https://github.com/pouchdb-community/pouchdb-adapter-fs) as a drop-in replacement for CouchDB to make the install easier. We can use the very same adapter on Glitch because Glitch allows for write access to the file system. So we don’t need CouchDB but still have permanent saving of data. It just isn’t very performant but should be good enough :)

**Comment by fozy81** [comment]
Thanks, I understand now. That's a really neat feature.

**Comment by fozy81** [comment]
Hi @gr2m , I've tried using https://github.com/gr2m/glitch-github-app but getting a bug. Looks like the github repo has copied into glitch but getting an error message in logs:

`/etc/app-types/node/start.sh: line 43: hoodie: command not found`

I've imported hoodie-app-tracker repo direct from github and that's working okay - but obviously this isn't continuously integrating:

https://powerful-sausage.glitch.me/   - looks great!

**Comment by gr2m** [comment]
@fozy81 Thanks for looking into it! I’d like to try something else but need a moment myself to have a look into it. I’ll be very busy until Thursday, I’ll get back to you then :)

**Comment by fozy81** [comment]
@gr2m I saw that 'now' deployment can be linked to github for continuous integration. So could try to deploy there for short-term? (I think Glitch would be better longterm). I've got a free cloudant account so could add that for backend or just keep it with local storage only?

**Comment by gr2m** [comment]
sure feel free to give that a try 👍 Let me know if I have to do something

**Comment by gr2m** [comment]
I see it listed in the list of installed services, go ahead and add now.json if needed 👍

**Comment by fozy81** [comment]
see json.now PR https://github.com/hoodiehq/hoodie-app-tracker/pull/186  :smile: 
and deployment shouold update here https://hoodie-app-tracker.now.sh/
This deployment won't allow user sign-out or store info in the cloud but it's a good demo and stores locally on device.

**Comment by gr2m** [comment]
awesome :) I think we can close this issue now?

**Comment by fozy81** [comment]
@gr2m :hand: Can you update the website 'Default Hoodie App...' link on the hoodiehq/hoodie-app-tracker repo home page from https://tracker.hood.ie/ to https://hoodie-app-tracker.now.sh/  ? :+1:

**Comment by gr2m** [comment]
Done 👍 Also invited you to the maintainers team! Sorry I thought you’d be a member already 🎉

**Comment by fozy81** [comment]
:fireworks: Woo, thanks for finding the time! And nice to hear your good news on twitter, all the best to you all. :+1:. So we've done it, offline first demo progressive web app with service worker and app manifest goodies!
