### ISSUE TITLE
Enter Item before Amount

### ISSUE THREAD

**Issue by fozy81** [hoodiehq/hoodie-app-tracker#179]
After testing the app, I wondered if it's more user friendly to enter the item before the amount. I'll maybe put together a pull request to test this change out.

:smile:

**Comment by gr2m** [comment]
Yeah why not :)

**Comment by fozy81** [comment]
see https://github.com/hoodiehq/hoodie-app-tracker/pull/181

**Comment by gr2m** [comment]
done via #181 ✌️
