### ISSUE TITLE
Number input currently cuts off numbers

### ISSUE THREAD

**Issue by jsimplicio** [hoodiehq/hoodie-app-tracker#18]
On latest Safari browser:
![screen shot 2016-02-27 at 12 47 33 pm](https://cloud.githubusercontent.com/assets/7318958/13374652/93eddfa2-dd50-11e5-9f7f-1d903e378097.png)

**Comment by nickcolley** [comment]
Guessing if we just remove https://github.com/hoodiehq/hoodie-app-tracker/blob/master/www/assets/app.css#L48 this'll be sorted.

**Comment by jsimplicio** [comment]
@nickcolley Thanks! This should be fixed now inside of the current PR.
