### ISSUE TITLE
Visual & Accessibility Improvements

### ISSUE THREAD

**Issue by Charlotteis** [hoodiehq/hoodie-app-tracker#20]
Hey Hey! I took a look.

Usability wise: great, simple, nice.
Noticed a few bugs visually (Chrome):

<img width="518" alt="stracker-mobile-bugs" src="https://cloud.githubusercontent.com/assets/542140/13374989/353c395e-dd8c-11e5-9e64-f4b51a782b59.png">

1. On Mobile devices, the links would look better aligned left
1. The text in the 'amount' input box gets cut off a lot. Mobile & Desktop. Issue #18
1. The about page calls this app 'Stracker', so should the title say 'Stracker' too? _Edit: I opened #21 to change the lone 'Stracker' to 'Tracker'_

<img width="608" alt="stracker-desktop-bugs" src="https://cloud.githubusercontent.com/assets/542140/13374990/353d86a6-dd8c-11e5-82bd-9db1361cde91.png">

1. On larger-than-mobile, the nav links are not aligned to the top of the header and it looks a little odd.
1. Particularly on mobile, the two links look too close together. Capitalising "About" and changing the email to "Account" might help this. 

<img width="614" alt="stracker-contrast" src="https://cloud.githubusercontent.com/assets/542140/13375041/76dc2012-dd8d-11e5-87d5-01957380b5cf.png">

1. The thin orange text on a white background is not contrasted well enough, meaning it is potentially difficult to see for folk with visual impairment. Could we use a darker orange?

<img width="414" alt="stracker-hidden-links" src="https://cloud.githubusercontent.com/assets/542140/13375051/9795b80e-dd8d-11e5-8338-5c2e59348ac2.png">

1. There are number of links not visible to the user (such as the log-in/forgot password links when signed in) that are still visible to screenreaders. This will offer a sub-optimal experience to those using assistive technologies. Using `aria-hidden="true"` can hide something from a screenreader so that it will not be read out. It might not work on all devices, but these are the trade offs we make when we build Single Page Web Apps. Aria-hidden should hopefully fix it for most people. http://www.456bereastreet.com/archive/201205/hiding_visible_content_from_screen_readers_with_aria-hidden/

I hope this make sense. Didn't PR it myself but can help if needed :sun_with_face:

**Comment by Charlotteis** [comment]
I used khan.github.io/tota11y/ to find the accessibility bugs, btw.

**Comment by gr2m** [comment]
wow awesome review, thanks @Charlotteis :+1:

**Comment by jsimplicio** [comment]
@Charlotteis for the header, instead of top aligned, is middle aligned cool too? Like I fixed it this way, they're exactly middle of `<header>`
![screen shot 2016-03-01 at 12 38 51 pm](https://cloud.githubusercontent.com/assets/7318958/13437542/5f8c52c8-dfaa-11e5-9707-a2c6f76bdfac.png)

**Comment by jsimplicio** [comment]
@Charlotteis Can you expand upon `aria-hidden`. Do we need to add that as `true` for elements that are still on the DOM but visibly hidden?

**Comment by nickcolley** [comment]
I'm not sure that we need aria-hidden for the hidden links, `display: none` will hide it from both our screenreader users and regular users.

I've started a branch with some tweaks from my testing in a screenreader (I'm using Chrome Vox for this): https://github.com/hoodiehq/hoodie-app-tracker/pull/27

My main concern is that when navigating to some of the sub-views (for example 'Change Username') the screenreader gives no indication that we have changed view.

This is in contrast to when you change pages (for example to the about page) where the title is read out and the first element is automatically focused.

I'm not entirely sure the best way to solve this kind of issue - if we programmatically focus an element in the new view if that would suffice.

aria-live doesn't seem to be good for this here either, so need to keep researching.

**Comment by jsimplicio** [comment]
Then I'm not sure what @Charlotteis is talking about. If we need or not `aria-hidden`. I just don't quite understand how to use it.

**Comment by Charlotteis** [comment]
Hey @jsimplicio, you can ignore my request for "aria-hidden". 'display: none' in the CSS will mean that the elements are hidden off page and wont be accessible via a screen reader, @nickcolley is right.

> Do we need to add that as true for elements that are still on the DOM but visibly hidden?

That was what I expected to happen, yeah :)

Middle aligning the header also looks good to me!

**Comment by nickcolley** [comment]
Did some digging and came across https://vimeo.com/117614181.

The way they describe solving the problem is as follows:
- Create a container in the page that is never added/removed with aria-live on it, this is our announcement container.
- Create an 'announce' script that can update that announcement container with content that the screenreader will automatically read without altering focus.
- To simulate a new page, update the `document.title` and send '`document.title` + page loaded' to the announce script which is similar to what happens when you trigger a real page load.

Let me know if someone else wants to have a bash at it otherwise I'll implement :smile_cat:

**Comment by nickcolley** [comment]
I think we've addressed everything here, going to close out, if there's any more let's keep them in small actionable issues.

thanks @Charlotteis @jsimplicio :love_letter:  :+1:
