### ISSUE TITLE
Color change?

### ISSUE THREAD

**Issue by jsimplicio** [hoodiehq/hoodie-app-tracker#28]
I know the orange wasn't very good for visual reasons but this purple shows very very dark on my macbook pro (from 2010 so not retina). I'm sure the purple will show this dark for other users too. For example under account settings I can barely tell I'm hovering an item because the purple active on hover color is so dark. How about we decide on another hoodie color that is 'more visible' but yet not too shocking like the orange?

I really like the green we use for our blog http://hood.ie/blog/ but am open to other suggestions!

**Comment by Charlotteis** [comment]
My first thought was "green", lets try it! :)

**Comment by nickcolley** [comment]
Could also use blue, people are used to seeing links in blue.

**Comment by Charlotteis** [comment]
> Could also use blue, people are used to seeing links in blue.

a great point, as always

**Comment by jsimplicio** [comment]
Is this the hoodie blue? http://hood.ie/get-help if so it feels a bit dark to me like the purple too.

**Comment by nickcolley** [comment]
The main website has no hover state changes so I guess we could take some liberty on that part and choose a lighter starting colour?

**Comment by jsimplicio** [comment]
Were you thinking a shade of blue? :)

**Comment by nickcolley** [comment]
I'm with you on any colour changes as long as it's got good contrast, green or not :)

**Comment by gr2m** [comment]
don’t worry about the Hoodie Colors too much, I’ve heard from other designers they are a pain in the butt because they are so hard to combine :) You can alter them, especially if it’s good for accessibility. You can put in some of your own preference, you’ve put in the most work after all :)

**Comment by jsimplicio** [comment]
Okay now we use `blue` which is high contrast at all sizes AAA. This should be :+1:

**Comment by gr2m** [comment]
yes, well done :) We can make follow up issues if there is room for farther improvements
