### ISSUE TITLE
add favicon.ico

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-app-tracker#30]
At least chrome currently logs errors in the console like this:

<img width="814" alt="screen shot 2016-03-05 at 14 31 40" src="https://cloud.githubusercontent.com/assets/39992/13549916/04937d3c-e2df-11e5-855d-b295e8b7c4f7.png">

Simplest would be to use a [transparent favicon.ico](http://transparent-favicon.info/favicon.ico) until someone wants to make a custom one :)

**Comment by jsimplicio** [comment]
Should we just use the one we got at http://hood.ie?

**Comment by nickcolley** [comment]
Could be confusing since this app isn't really hoodie related.

https://github.com/hoodiehq/hoodie-app-tracker/pull/33

**Comment by finnp** [comment]
Closed, because Favicon was added in #33 :balloon:
