### ISSUE TITLE
bug: Hitting save closes all open edit inputs

### ISSUE THREAD

**Issue by jsimplicio** [hoodiehq/hoodie-app-tracker#45]
If you hit edit on many items and then save on only one, the save will close out of the edit view for all items not just the one you clicked.

**Comment by vickenliu** [comment]
@jsimplicio  i think this is not a bug,or maybe we need to redesign the UX, at the moment, the list view is re-render after any item has been changed,  (if use React, this will be very easy to solve)
it means, after ONE item data change event fired, the previous view (that you clicked many edit of the items) is replaced by the new view of new set of data rendered to the DOM.

**Comment by fozy81** [comment]
PR Allow only one item to be edited at a time https://github.com/hoodiehq/hoodie-app-tracker/pull/177 - This avoids the issue of editing multiple items and the edits not being saved
