### ISSUE TITLE
type error with 'url' parameter on initial install

### ISSUE THREAD

**Issue by jywarren** [hoodiehq/hoodie-app-tracker#49]
I'm just trying to install this at SpinachCon, and once I got node 4.4.0 installed, i ran `npm start`, but I got this error:

https://gist.github.com/jywarren/d04d10a83c2e4bec2470

Key excerpt:

````js
ERR! config options.dbUrl must be set. PouchDB not supported at this point.
url.js:90
    throw new TypeError("Parameter 'url' must be a string, not " + typeof url);
    ^

TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:90:11)
    at Object.urlParse [as parse] (url.js:84:5)
    at removeAuth (/home/warren/sites/hoodie-app-tracker/node_modules/hoodie/node_modules/hoodie-server/lib/hapi.js:60:30)
````

I'm on ARM7 (a chromebook) so this may not be relevant to your typical contributor, but I thought I'd share in case it's helpful. Thanks!

**Comment by gr2m** [comment]
I’ll look into it

**Comment by gr2m** [comment]
this should be resolved now. Could you please try to setup from scratch?
https://github.com/hoodiehq/hoodie-app-tracker#setup

**Comment by gr2m** [comment]
please reopen if the issue persists

**Comment by jywarren** [comment]
Thanks, had a very busy few days and will circle back and confirm soon,
reopening if I have trouble.

**Comment by jywarren** [comment]
Great, it installed and `npm start` worked, i was able to sign up and create issues. 

However, the output was a bit verbose: https://gist.github.com/jywarren/7bfee91adacb47cce365

Thanks!

**Comment by gr2m** [comment]
thanks! I’ve seen the output before, should be fine :tm:

Might be related that you use `npm@2`, we recommend `npm@3`. You can update npm with `npm install --global npm`
