### ISSUE TITLE
401 not Authorized Bug upon starting the app.

### ISSUE THREAD

**Issue by sebbel** [hoodiehq/hoodie-app-tracker#51]
I have cloned the repository and ran the couchdb docker container, but added a -p 5984:5984 so I could access Futon on localhost:5984.
I also added a .hoodierc containing the dbUrl: "http://admin:secret@localhost:5894" and logged into Futon and created the admin account admin:secret.

After npm start, when I load the page, I am getting a 401 not authorized error:
"Unauthorized", message: "Name or password is incorrect."

Xubuntu 15
npm -v 
3.7.3
node -v 
5.9.1

**Comment by gr2m** [comment]
> After npm start, when I load the page, I am getting a 401 not authorized error

That sounds like you were logged in to an account before in your browser, otherwise Hoodie wouldn’t try to send any requests. Check if `hoodie.account.id` returns a string. If it does, do `localStorage.clear()` and reload the page, that should help

**Comment by sebbel** [comment]
Managed to get it working. A full reset of browser AND couchdb helped.

**Comment by gr2m** [comment]
glad to hear :)
