### ISSUE TITLE
session error

### ISSUE THREAD

**Issue by vickenliu** [hoodiehq/hoodie-app-tracker#70]
Hi, i was trying to see anything i can contribute, I met some troubles:

1, i can successfully create new account

2,but when i try to change email / delete account / change password it alerts 'session invalid'

3, also i can not sign out.

I have checked the files, couldnt find out what s wrong, maybe the hoodi 's problem ?

thanks

**Comment by gr2m** [comment]
Thanks @vickenliu I will look into it!
