### ISSUE TITLE
XSS: Data is not encoded on displaying

### ISSUE THREAD

**Issue by oliverklee** [hoodiehq/hoodie-app-tracker#73]
The data needs to be HTML-encoded upon displaying.

Steps to reproduce: 
1. enter any item
2. enter the Item

```
</td></tr>
```
1. watch the HTML break

**Comment by gr2m** [comment]
Great, thanks so much Oliver! Can you send a PR to fix it? Happy to assist if you have any questions :)

**Comment by sdvg** [comment]
Fixed in #80
