### ISSUE TITLE
Improve UX for new Hoodie users

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-app-tracker#8]
The "Something Tracker" will be the first people will experience when they give Hoodie a try. So that experience is very important to us.

### Current state

We didn’t put too much thought into the user experience, we only needed something to test the new Hoodie.

![something-tracker](https://cloud.githubusercontent.com/assets/39992/13094743/c435246e-d4da-11e5-8b14-249f3b50c63d.png)

### Goal

"Something Tracker" is the most basic app we could come up with to demo Hoodie’s data & account capabilities. We intentionally decided to leave open what the user wants to track, like time or expenses.

The target group are developers of all skill levels. Most of them are thinking about building an own app with Hoodie, and will use the Something Tracker app for evaluation. We want to make this experience as enjoyable as possible.

#### Features

The user should be able to:

- track something with an amount and a note, both are required
- see all the tracked items
- edit an existing item
- remove a single item
- remove all items at once
- sign up for an account
- sign in to an existing account
- sign out
- destroy an account
- change username
- change password
- reset password

#### Notes 

- The app should work great in [all current browsers](http://pouchdb.com/learn.html#browser_support), on desktops, laptops, tablets and phones alike.
- The user should be able to add / update / remove items without an account.
- When signed in, the list of displayed items should update when changes are synchronised from remote (you can simulate that by opening http://localhost:8080 as well as http://127.0.0.1:8080 and login in both with the same user account)
- show a message if the user is unauthenticated (see `.hasInvalidSession()` and the `unauthenticate` event at https://github.com/hoodiehq/hoodie-client-account)
- show a message if the user is offline (`hoodie.connectionStatus.*`, see https://github.com/hoodiehq/hoodie-client-connection-status)

Features / Notes are suggestions from our side. If you have any suggestions to improve the experience for the target group, we are ears :dog:

**Comment by gr2m** [comment]
One idea I had was an "about" page, where we explain what this app is and why it is like it is, what Hoodie is, and link places like the Hoodie chat for questions, or the [Hoodie Contributors landing page](https://github.com/hoodiehq/discussion/issues/90)

**Comment by nickcolley** [comment]
@gr2m looks like there's been good progress in this respect, do you think we could close this in favour of smaller more specific issues so it's more actionable?

**Comment by gr2m** [comment]
yessir, good call. And thanks for the great work :+1:
